# Generated by Django 3.1.6 on 2021-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210209_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='maker',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
