# Generated by Django 3.1.6 on 2021-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_games_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='skill_level',
            field=models.IntegerField(null=True),
        ),
    ]
